files:
  - source: '*.resx'
    ignore:
      - '*.*.resx'
    translation: /%original_path%/%file_name%.%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        ru: ru
        pt-BR: pt-BR
