version: 11.2.1.{build}
image: Visual Studio 2015
configuration:
- Release
- Debug
platform: Any CPU
shallow_clone: true
before_build:
- ps: >-
    Invoke-WebRequest "$env:APIKeys" -OutFile "ShareX.UploadersLib\APIKeys\APIKeysLocal.cs"

    nuget restore
build:
  project: ShareX.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: ShareX\bin\Release
  name: Release
- path: ShareX\bin\Debug
  name: Debug